### ISSUE TITLE
Error in go_enrich function

### ISSUE THREAD

**Issue by subinoy** [sgrote/GOfuncR#1]
I am getting an error while running go_enrich function with background data.frame as below
> res_hyper_bg = go_enrich(input_hyper_bg)
Checking arguments...
Error in go_enrich(input_hyper_bg) : 
  Genes with multiple assignment in input: AADAT, ABCA10, ABCA13, ABCA6, ABCA8, ABCA9, ABCC3, ABCC8, ABI3BP, ACE, ACKR1, ACKR3, ACOX2, ACPP, ACSM5, ACSS3, ACTA2, ACTA2-AS1, ACVR1, ACVR1C, ACVR2A, ACVRL1, ADAM12, ADAM19, ADAM28, ADAM8, ADAMDEC1, ADAMTS1, ADAMTS10, ADAMTS17, ADAMTS7, ADAMTS9, ADAMTS9-AS1, ADAMTS9-AS2, ADAMTSL3, ADAP1, ADCY2, ADCY3, ADCY5, ADCY6, ADD2, ADGRA2, ADGRB2, ADGRB3, ADGRD1, ADGRE1, ADGRE3, ADGRG2, ADGRG3, ADGRG4, ADGRL2, ADGRL3, ADH1B, ADH1C, ADIPOQ, ADIPOQ-AS1, ADIRF, ADPRHL1, ADRB1, AEBP1, AFAP1, AFAP1-AS1, AFAP1L2, AGAP11, AGPAT9, AGT, AGTR1, AHSP, AIF1, AIM1L, AJUBA, AKAP12, AKR1C8P, ALB, ALDH1A3, ALDH7A1, ALOX5, ALOX5AP, ALPK2, ALPL, ALS2CL, ALS2CR11, ALX1, ALX4, AMICA1, AMIGO1, AMOTL2, AMPD3, ANGPT1, ANGPT4, ANGPTL1, ANGPTL2, ANGPTL4, ANK1, ANK2, ANK3, ANKRD18A, ANKRD22, ANKRD35, ANKRD36BP2, ANKRD55, ANKRD65, ANO2, ANO3, ANO5, ANO8, ANOS1, ANTXR1, ANXA3, AOAH, AOC3, AOX1, APBB2, APLN, APOB, APOBEC3B, APOBEC3B-AS1, APOBR, APOD, APOE, AQP7, AQP9, AR,
>

**Comment by sgrote** [comment]
Hi,
did you maybe inlcude the candidate genes also in the background gene set? I.e. do you have two entries per candidate gene in 'input_hyper_bg', one with a '1' in the second column and one with a '0'?
This would cause the error-message. It is not necessary to define candidate genes also as background, because they are implicitly inlcuded in the background. The input should have only one value per gene. Let me know if this doesn't solve the problem.
Cheers, Steffi
