### ISSUE TITLE
question about refinement P-value

### ISSUE THREAD

**Issue by capricy** [sgrote/GOfuncR#5]
Hi GOfuncR contributors,

I have question about this tool. I am working on enrichment analysis for a geneset and tried to run the "refine" function from the GOfuncR package. I noticed that different GO categories used different p-value threshold for significance (as shown in the screenshot). My question is: how this threshold was selected? Can I have my own threshold?
 
I also post this question on bioconductor support site:
 
question about the refined outputs from GOfuncR package
 
Thanks.
 
Kind regards,

C.

====ScreenShot====

![image](https://user-images.githubusercontent.com/18124356/139064367-f040454d-442d-458e-8a3e-dff1ac6ec84a.png)

**Comment by sgrote** [comment]
Hi Caprici,

the threshold for the significance is based on the FWER, which you can modify using the `fwer` parameter of the `refine` function. The p-value that is printed to the console corresponds to this FWER. Since the three GO-domains are analyzed seperately, the same FWER likely corresponds to different p-values for each domain.  

The refinement is based to on the p-value and not the FWER, because GO-terms are re-tested for significance after removing genes from significant child-terms (see the elim algorithm as described in https://academic.oup.com/bioinformatics/article/22/13/1600/193669), and this does not involve a re-calculation of the FWER.

Best,
Steffi
